### ISSUE TITLE
java.lang.IllegalStateException: find failed: jar=E:\ideaworkspace\unidbg_mt\unidbg-server-main\target\unidbg-server-1.0.0.jar, jarEntryName=BOOT-INF/classes, name=android/sdk23/dev/__properties__, foundEntry=null

### ISSUE THREAD

**Issue by zhang1201234** [cxapython/unidbg-server#11]
当我直接运行项目的时候，访问都没问题，但是打包成jar包后，发起请求会出异常。
[main] INFO com.github.unidbg.linux.AndroidElfLoader - libdumpcrash.so load dependency libandroid.so failed
[main] WARN com.github.unidbg.linux.ARM64SyscallHandler - handleInterrupt intno=2, NR=56, svcNumber=0x0, PC=RX@0x4025a6a4[libc.so]0x6a6a4, LR=RX@0x40212854[libc.so]0x22854, syscall=null
java.lang.IllegalStateException: find failed: jar=E:\ideaworkspace\unidbg_mt\unidbg-server-main\target\unidbg-server-1.0.0.jar, jarEntryName=BOOT-INF/classes, name=android/sdk23/dev/__properties__, foundEntry=null
        at com.github.unidbg.utils.JarURL.create(JarURL.java:51)
        at com.github.unidbg.utils.ResourceUtils.isFile(ResourceUtils.java:104)
        at com.github.unidbg.utils.ResourceUtils.extractResource(ResourceUtils.java:22)
        at com.github.unidbg.linux.android.AndroidResolver.resolve(AndroidResolver.java:100)
        at com.github.unidbg.unix.UnixSyscallHandler.resolve(UnixSyscallHandler.java:95)
        at com.github.unidbg.unix.UnixSyscallHandler.open(UnixSyscallHandler.java:310)
        at com.github.unidbg.linux.ARM64SyscallHandler.openat(ARM64SyscallHandler.java:1274)
        at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:139)
        at com.github.unidbg.arm.backend.InterruptHookNotifier.notifyCallSVC(InterruptHookNotifier.java:14)
        at com.github.unidbg.arm.backend.dynarmic.DynarmicBackend64.callSVC(DynarmicBackend64.java:42)
        at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Native Method)
        at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Dynarmic.java:61)
        at com.github.unidbg.arm.backend.DynarmicBackend.emu_start(DynarmicBackend.java:76)
        at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:370)
        at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:446)
        at com.github.unidbg.arm.AbstractARM64Emulator.eInit(AbstractARM64Emulator.java:232)
        at com.github.unidbg.linux.AbsoluteInitFunction.call(AbsoluteInitFunction.java:55)
        at com.github.unidbg.linux.LinuxModule.callInitFunction(LinuxModule.java:123)
        at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:202)
        at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:63)
        at com.github.unidbg.spi.AbstractLoader.load(AbstractLoader.java:219)
        at com.github.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:295)
        at com.crack.MT.<init>(MT.java:67)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
        at com.UnidbgServerApplication.main(UnidbgServerApplication.java:11)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

**Comment by GreyFeatherVoid** [comment]
你是不是切换了unidbg的版本，我用0.9.6也报这个错，换成0.9.7就好了
